# Generated by Django 5.1.4 on 2024-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_location_hotel_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
