services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=awmproject.settings
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webmap
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
