# Generated by Django 5.1.4 on 2024-12-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisine',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
